name: Actualizar Datos de Sismicidad EMSC

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: actualizaciones-datos
  cancel-in-progress: false

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Crear carpeta de datos si no existe
        run: mkdir -p datos

      - name: Consultar API EMSC
        run: |
          curl -fLsS "https://www.seismicportal.eu/fdsnws/event/1/query?format=json&minlatitude=35.5&maxlatitude=39.0&minlongitude=-7.5&maxlongitude=-2.0&limit=1" > datos/sismicidad.json

      - name: Comprobar cambios
        id: cambios
        run: |
          if git diff --quiet -- datos/sismicidad.json; then
            echo "cambios=false" >> "$GITHUB_OUTPUT"
            echo "No se detectaron cambios."
          else
            echo "cambios=true" >> "$GITHUB_OUTPUT"
            echo "Se detectaron cambios."
          fi

      - name: Commit cambios
        if: steps.cambios.outputs.cambios == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git rebase origin/main

          git add datos/sismicidad.json
          git commit -m "Automatización: Datos sísmicos actualizados [skip ci]"

          git push origin HEAD:main

          git commit -m "Automatización: Datos sísmicos actualizados [skip ci]"

          git push origin main
